// The pool of PvP deathmatch arenas and the per-match random pick.
//
// Every arena in the pool is fully symmetric across both axes (generated by
// tools/genPvpArena.mjs), so whichever one a match lands on, all four corner
// spawns face identical cover, weapons and hazards. Picking a random arena per
// match keeps deathmatches fresh without ever giving anyone a head start.
//
// The host decides; guests follow through the normal zoneChange/snapshot path
// (they load whatever zone the host travelled to), so this never crosses the
// wire. The offline controller and the online host both read currentPvpArena()
// when loading, and re-roll with pickPvpArena() on each match start / rematch.

import { PVP_ARENA_ZONE_ID } from "./constants.js";

// 1301 is the original hand-built arena; 1302..1304 are the generated ones.
export const PVP_ARENA_ZONE_IDS = [PVP_ARENA_ZONE_ID, 1302, 1303, 1304];

// The arena chosen for the current match. Defaults to the original so any
// pre-pick read (or a path that never calls pickPvpArena) is still valid.
let current = PVP_ARENA_ZONE_ID;

// Test/debug override: when set, pickPvpArena() always returns this id, so the
// e2e suite can pin a known arena (and assert on its fixed pickups). Cleared
// with null.
let forced = null;

export function isPvpArenaZone(id) {
  return PVP_ARENA_ZONE_IDS.includes(id);
}

// Choose (and remember) the arena for the next match. Honors the test override
// when one is set, otherwise picks uniformly at random from the pool.
export function pickPvpArena() {
  if (forced != null && isPvpArenaZone(forced)) {
    current = forced;
  } else {
    current = PVP_ARENA_ZONE_IDS[Math.floor(Math.random() * PVP_ARENA_ZONE_IDS.length)];
  }
  return current;
}

export function currentPvpArena() {
  return current;
}

export function setForcedPvpArena(id) {
  forced = id == null ? null : (id | 0);
}
