[package]
name = "game"
version = "1.2.5"
edition = "2021"

[dependencies]
game_core = { path = "../game_core" }
raylib = "5.0.2"
common_macros = "0.1.1"
sys-locale = "0.3.1"
open = "5.3.1"

[[bin]]
name = "game"
path = "src/main.rs"

[build-dependencies]
winresource = "0.1.17"
