[package]
name = "dungen"
version = "1.0.0"
edition = "2021"

[dependencies]
game_core = { path = "../game_core" }
clap = { version = "3.1", features = ["derive"] }
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[[bin]]
name = "dungen"
path = "src/main.rs"
