[package]
name = "mapgen"
version = "1.0.0"
edition = "2021"

[dependencies]
game_core = { path = "../game_core" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
image = "0.24"
regex = "1.5"

[[bin]]
name = "mapgen"
path = "src/main.rs"
